# Site settings
title: Personal Webpage of David Duggins
description: >
    Well, I was born on a normal day in July, 1981 and have been creating chaos ever since. 
    Born in North Carolina, but raised in the aftermath of the Soviet Union, Kazakhstan, 
    I have been messing around with computers nearly my entire life. I wrote my first program 
    in assembly when I was 11. In my early teens I ran a BBS connected to Fidonet and started 
    building a website for my band. In 1999 I was introduced to Linux, and it was love at first compile. 
    I started my career in IT in the early 2000's doing IT for a Car Dealership in Charlotte NC. 
    I wrote my first major web app in Cold Fusion (an ecom app) at that time. 
    In 2006 I left Charlotte and moved down to Columbia where starting working as a developer, freelancer and consultant.
    Currently I am working as a freelance developer and DevOps consultant!!

 
url: 'https://weatheredwatcher.github.io'
baseurl: ''
google_analytics: 'G-0H2CLMW2VQ'
disqus_shortname: 'weatheredwatcher'
site_build_version: 30 # Use this to bump a build if needed
author:
  name: 'David Duggins'
  email: david@duggins.net
  # twitter_username: davidduggins
  cv_path: resume
  #reddit_username: weatheredwatcher
  github_username:  weatheredwatcher
  linkedin_username:  davidduggins

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
        comments: false

collections:
  projects:
    output: true
    permalink: /:collection/:title

maps:
    google:
      api_key: AIzaSyAKIUZyazA30kSvO1L7_ddfRZ434kVYWzQ

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed
kramdown:
  # use Github Flavored 
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-leaflet

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor']
