# Site settings
title: Personal Webpage of David Duggins
description: >
    I work as a senior php developer for a site that teaches how to play the guitar
    My interests include: playing TTRPG such as Pathfinder and D&D, playing the guitar and
    reading books..
url: 'https://weatheredwatcher.github.io'
baseurl: ''
# google_analytics: 'UA-167128850-1'
disqus_shortname: 'weatheredwatcher'

author:
  name: 'David Duggins'
  email: david@duggins.net
  # twitter_username: davidduggins
  cv_path: assets/duggins-resume.pdf
  reddit_username: weatheredwatcher
  github_username:  weatheredwatcher
  #  linkedin_username:  davidduggins

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
        comments: false

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor']
